query GetPostBySlug($slug: String!) {
  post(where: { slug: $slug }) {
    id
    title
    content {
      html
      text
      markdown
    }
    slug
    coverImage {
      id
      url
    }
    author {
      id
      name
      picture {
        id
        url
      }
    }
    date
  }
}
