import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from "graphql-request";

const graphcms = new GraphQLClient(process.env.GQL_API_URL)

const QUERY = gql`
  {
    posts {
      id
      title,
      author {
        name
      }
    }
  }
`
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return { props: { posts } }
}
export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {posts.map(post => {
            return (
              <div key={post.id}>
                <div className='text-3xl font-bold underline'>{post.title}</div>
              </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}
