import Head from 'next/head'
import { GraphQLClient, gql } from "graphql-request";
import Image from 'next/image'
import Link from 'next/link';

const graphcms = new GraphQLClient(process.env.GQL_API_URL)

export const QUERY = gql`
  {
    posts {
      id
      title
      excerpt
      slug
      coverImage {
        id
        url
      }
      author {
        id
        name
      }
      date
    }
  }
`
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return { props: { posts } }
}
export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Next post app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-16 bg-gray-100">
        <div>
          {posts.map(post => {
            return (
              <Link key={post.id} as={`/post/${post.slug}`} href="/post/[slug]">
                <a
                  className="max-w-lg shadow-lg mb-16 rounded-lg mx-auto flex"
                >
                  <div
                    className="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden"
                    style={{ backgroundImage: `url(${post.coverImage.url})`, backgroundPosition: 'center center' }}
                    title={post.title}
                  ></div>
                  <div className="bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
                    <div className="mb-8">
                      <div className="text-gray-900 font-bold text-xl mb-2">
                        {post.title}
                      </div>
                      <p className="text-gray-700 text-base">{post.excerpt}</p>
                    </div>
                    <div className="flex items-center">
                      <div className="text-sm">
                        <p className="text-gray-900 leading-none">
                          {post.author.name}
                        </p>
                        <p className="text-gray-600">{post.date}</p>
                      </div>
                    </div>
                  </div>
                </a>
              </Link>
            )
          })}
        </div>
      </main>
    </div>
  )
}
